// SPDX-License-Identifier: MIT
/**
 * What the recovery page says, in both languages. The long explanations are in
 * the template, one block per language; these are the short things — labels,
 * buttons, and the lines the log writes.
 *
 * German without address, as on lora.le-space.de: no du, no Sie.
 */
export const WORDS = {
  en: {
    title: "recovery — a list that survives the phone",
    status: { todo: "not yet", running: "running…", done: "done", failed: "failed" },
    showDetails: "Show the technical details",
    hideDetails: "Hide the technical details",
    touch: {
      1: "Touch 1 of 3 — the key's secret for this site (with PIN)",
      2: "Touch 2 of 3 — a second signature, to recover the public key",
      3: "Touch 3 of 3 — the passkey vouches for the signing key (with PIN)",
    },
    step1: "Tell the page who you are",
    yourKey: "your security key",
    nothingOnline: "— nothing goes on the internet",
    asking: "asking the key…",
    askAgain: "Ask again",
    useKey: "Use my security key",
    compareHint:
      "To compare two phones, show the technical details: the two lines there must be the same on both.",
    didFingerprint: "DID fingerprint",
    keyFingerprint: "signing key fingerprint",
    differ:
      "If they differ, the identity did not travel and nothing below proves anything — usually the wrong passkey was picked.",
    step2: "Your list",
    open: "open",
    empty: "nothing in it yet",
    newEntry: "new entry",
    placeholder: "Buy milk…",
    add: "Add",
    makeListHint:
      "On phone A: make the list, and write a few entries. On phone B: skip this and go to step 5 — the list comes back here.",
    makeList: "Make the list",
    needsStep1: "Needs step 1 first.",
    nobody: "nobody",
    staysHere: "— it stays on this phone until step 3",
    step3: "Put it somewhere safe",
    theFile: "the file, no account",
    thePointer: "the pointer",
    backingUp: "backing up…",
    backUp: "Back up and publish the pointer",
    needsList: "Needs a list first.",
    pointer: "pointer",
    backup: "backup",
    blocks: (n) => `${n} blocks`,
    step4: "Lose the phone",
    forget: "Forget everything on this phone",
    step5: "Get it back",
    gateways: "Aleph's gateway",
    whereTo: "Where the backup goes",
    services: { aleph: "Aleph", pinata: "Pinata", lighthouse: "Lighthouse" },
    noAccount: "no account needed",
    keyPlaceholder: "your API key",
    gatewayPlaceholder: {
      pinata: "your gateway, e.g. silver-fox.mypinata.cloud",
      lighthouse: "your gateway, e.g. preferred-cat.lighthouseweb3.xyz",
    },
    keysStay: "Keys stay in this browser and are sent to that service only.",
    forgetKeys: "forget them",
    needsKeyFor: (names) => `Needs a key for ${names}.`,
    pathGateway: "HTTP gateway",
    pathPeers: "IPFS over libp2p",
    pathUnused: "not needed",
    peersConnected: (n) => (n === 1 ? "1 peer" : `${n} peers`),
    fileOnly: "the file",
    restoring: "restoring…",
    getBack: "Get my list back",
    needsStep1SameKey: "Needs step 1 first, with the same key.",
    back: "Your list is back, in step 2. Write an entry there to prove it is still yours.",
    whatHappened: "What happened",
    roadmap: "roadmap",
    howItWorks: "how it works",
    log: {
      failed: (name, error) => `! ${name} failed: ${error}`,
      asking: "asking the security key — three touches",
      identity: (did) => `identity: ${did}…`,
      running: "OrbitDB is running with that identity",
      listOpen: (address) => `list open: ${address}`,
      wrote: (text) => `wrote »${text}«`,
      backingUp: "backing up, and publishing the pointer…",
      published: (name, cid, blocks) => `pointer ${name} → ${cid} (${blocks} blocks)`,
      askingPointer: "asking for the pointer, with the key alone…",
      viaGateway: (ms, bytes) => `the gateway answered in ${ms} — ${bytes} bytes`,
      viaPeers: (ms, bytes, peers) =>
        `bitswap answered in ${ms} — ${bytes} bytes from ${peers === 1 ? "1 peer" : `${peers} peers`}`,
      gatewaySilent: "no answer",
      restored: (address, blocks) => `restored ${address} — ${blocks} blocks, nothing carried over`,
      gone: "everything on this device is gone — reloading",
      nothingStored: "nothing is stored here; the key is asked every time",
    },
  },
  de: {
    title: "Recovery — eine Liste, die das Telefon übersteht",
    status: { todo: "noch nicht", running: "läuft…", done: "erledigt", failed: "fehlgeschlagen" },
    showDetails: "Technische Details einblenden",
    hideDetails: "Technische Details ausblenden",
    touch: {
      1: "Berührung 1 von 3 — das Geheimnis des Schlüssels für diese Seite (mit PIN)",
      2: "Berührung 2 von 3 — eine zweite Signatur, um den öffentlichen Schlüssel zurückzugewinnen",
      3: "Berührung 3 von 3 — der Passkey bürgt für den Signierschlüssel (mit PIN)",
    },
    step1: "Identität vom Schlüssel",
    yourKey: "der Sicherheitsschlüssel",
    nothingOnline: "— nichts geht ins Internet",
    asking: "Schlüssel wird gefragt…",
    askAgain: "Erneut fragen",
    useKey: "Sicherheitsschlüssel verwenden",
    compareHint:
      "Zum Vergleich zweier Telefone die technischen Details einblenden: Die beiden Zeilen dort müssen auf beiden gleich sein.",
    didFingerprint: "DID-Fingerabdruck",
    keyFingerprint: "Fingerabdruck des Signierschlüssels",
    differ:
      "Weichen sie ab, ist die Identität nicht mitgekommen, und nichts weiter unten beweist etwas — meist wurde der falsche Passkey gewählt.",
    step2: "Die Liste",
    open: "offen",
    empty: "noch leer",
    newEntry: "neuer Eintrag",
    placeholder: "Milch kaufen…",
    add: "Hinzufügen",
    makeListHint:
      "Auf Telefon A: die Liste anlegen und ein paar Einträge schreiben. Auf Telefon B: diesen Schritt überspringen und zu Schritt 5 gehen — die Liste erscheint dann hier.",
    makeList: "Liste anlegen",
    needsStep1: "Braucht zuerst Schritt 1.",
    nobody: "niemand",
    staysHere: "— sie bleibt bis Schritt 3 auf diesem Telefon",
    step3: "In Sicherheit bringen",
    theFile: "die Datei, ohne Konto",
    thePointer: "der Zeiger",
    backingUp: "wird gesichert…",
    backUp: "Sichern und Zeiger veröffentlichen",
    needsList: "Braucht zuerst eine Liste.",
    pointer: "Zeiger",
    backup: "Sicherung",
    blocks: (n) => `${n} Blöcke`,
    step4: "Das Telefon verlieren",
    forget: "Alles auf diesem Telefon vergessen",
    step5: "Zurückholen",
    gateways: "Alephs Gateway",
    whereTo: "Wohin die Sicherung geht",
    services: { aleph: "Aleph", pinata: "Pinata", lighthouse: "Lighthouse" },
    noAccount: "ohne Konto",
    keyPlaceholder: "dein API-Schlüssel",
    gatewayPlaceholder: {
      pinata: "dein Gateway, z. B. silver-fox.mypinata.cloud",
      lighthouse: "dein Gateway, z. B. preferred-cat.lighthouseweb3.xyz",
    },
    keysStay: "Schlüssel bleiben in diesem Browser und gehen nur an diesen Dienst.",
    forgetKeys: "vergessen",
    needsKeyFor: (names) => `Braucht einen Schlüssel für ${names}.`,
    pathGateway: "HTTP-Gateway",
    pathPeers: "IPFS über libp2p",
    pathUnused: "nicht gebraucht",
    peersConnected: (n) => (n === 1 ? "1 Peer" : `${n} Peers`),
    fileOnly: "die Datei",
    restoring: "wird zurückgeholt…",
    getBack: "Liste zurückholen",
    needsStep1SameKey: "Braucht zuerst Schritt 1, mit demselben Schlüssel.",
    back: "Die Liste ist zurück, in Schritt 2. Ein neuer Eintrag dort zeigt, dass sie dieselbe Identität weiter annimmt.",
    whatHappened: "Was geschah",
    roadmap: "Roadmap",
    howItWorks: "so funktioniert es",
    log: {
      failed: (name, error) => `! ${name} fehlgeschlagen: ${error}`,
      asking: "Sicherheitsschlüssel wird gefragt — drei Berührungen",
      identity: (did) => `Identität: ${did}…`,
      running: "OrbitDB läuft mit dieser Identität",
      listOpen: (address) => `Liste offen: ${address}`,
      wrote: (text) => `geschrieben: »${text}«`,
      backingUp: "Sicherung läuft, der Zeiger wird veröffentlicht…",
      published: (name, cid, blocks) => `Zeiger ${name} → ${cid} (${blocks} Blöcke)`,
      askingPointer: "Zeiger wird erfragt, allein mit dem Schlüssel…",
      viaGateway: (ms, bytes) => `das Gateway hat in ${ms} geantwortet — ${bytes} Bytes`,
      viaPeers: (ms, bytes, peers) =>
        `Bitswap hat in ${ms} geantwortet — ${bytes} Bytes von ${peers === 1 ? "1 Peer" : `${peers} Peers`}`,
      gatewaySilent: "keine Antwort",
      restored: (address, blocks) => `zurückgeholt: ${address} — ${blocks} Blöcke, nichts mitgebracht`,
      gone: "alles auf diesem Gerät ist gelöscht — die Seite lädt neu",
      nothingStored: "hier ist nichts gespeichert; der Schlüssel wird jedes Mal gefragt",
    },
  },
};
